export const es = {
  'common.retry': 'Reintentar',
  'common.signOut': 'Cerrar sesión',
  'runtime.loading': 'Preparando vuestro espacio...',
  'runtime.configTitle': 'Pomelo necesita configuración',
  'runtime.configBody': 'Revisa el entorno de desarrollo y vuelve a intentarlo.',
  'runtime.networkTitle': 'No hemos podido conectar',
  'runtime.networkBody': 'Tu sesión sigue segura. Comprueba la conexión y reintenta.',
  'auth.title': 'Volved a vuestro Pomelo',
  'auth.body': 'Inicia sesión para verificar tu perfil y continuar.',
  'auth.email': 'Correo electrónico',
  'auth.password': 'Contraseña',
  'auth.submit': 'Iniciar sesión',
  'auth.failed': 'No hemos podido iniciar sesión. Revisa los datos e inténtalo de nuevo.',
  'preferences.language': 'Idioma',
  'preferences.appearance': 'Apariencia',
  'preferences.system': 'Sistema',
  'preferences.light': 'Claro',
  'preferences.dark': 'Oscuro',
  'home.wordmark': 'pomelo.',
  'home.openProfile': 'Abrir perfil',
  'home.streak': '6 días',
  'home.date': 'MARTES, 11 DE AGOSTO',
  'home.hero.answer.eyebrow': 'POM ESTÁ LISTO',
  'home.hero.answer.title': 'Hoy os toca\ncrear algo juntos.',
  'home.hero.answer.progress': '6 momentos juntos',
  'home.hero.waiting.eyebrow': 'TU PARTE ESTÁ LISTA',
  'home.hero.waiting.title': 'Esperando a\nLucía.',
  'home.hero.waiting.progress': '6 momentos juntos',
  'home.hero.ready.eyebrow': 'POM ESTÁ EMOCIONADO',
  'home.hero.ready.title': 'Ya podéis\ndescubrirlo.',
  'home.hero.ready.progress': '6 momentos juntos',
  'home.hero.complete.eyebrow': 'NUEVO RECUERDO',
  'home.hero.complete.title': 'Ya está en\nvuestra historia.',
  'home.hero.complete.progress': '7 momentos juntos',
  'moment.kind.question': 'PREGUNTA',
  'moment.kind.answered': 'RESPONDIDO',
  'moment.kind.ready': 'LISTO',
  'moment.kind.revealed': 'REVELADO',
  'moment.action.answer': 'Responder',
  'moment.action.remind': 'Avisar a Lucía',
  'moment.action.reveal': 'Descubrir el Momento',
  'moment.today': 'MOMENTO DE HOY',
  'moment.promptLabel': 'PREGUNTA DE HOY',
  'moment.prompt': '¿Qué pequeño gesto de Lucía te hizo sonreír esta semana?',
  'moment.privacy': 'Responderéis sin ver la respuesta del otro.',
  'moment.partnerPending': 'Lucía aún no ha respondido',
  'moment.saved': 'Respuesta guardada · esperando a Lucía',
  'moment.you': 'TÚ',
  'moment.partner': 'LUCÍA',
  'moment.ownAnswer': '“El café que me dejaste preparado.”',
  'moment.partnerLocked': 'Respuesta lista · todavía oculta',
  'moment.partnerAnswer': '“Cuando me abrazaste al llegar a casa y preparaste la cena.”',
  'moment.continue': 'Seguid hablando...',
  'moment.send': 'Enviar respuesta',
  'nav.home': 'Inicio',
  'nav.history': 'Historia',
  'nav.map': 'Mapa',
  'nav.pair': 'Pareja',
  'widget.title': 'Momento de hoy',
  'widget.action': 'Abrir Pomelo',
} as const;

export type TranslationKey = keyof typeof es;

export const en: Record<TranslationKey, string> = {
  'common.retry': 'Try again',
  'common.signOut': 'Sign out',
  'runtime.loading': 'Preparing your shared space...',
  'runtime.configTitle': 'Pomelo needs configuration',
  'runtime.configBody': 'Check the development environment and try again.',
  'runtime.networkTitle': 'We could not connect',
  'runtime.networkBody': 'Your session is safe. Check your connection and try again.',
  'auth.title': 'Come back to your Pomelo',
  'auth.body': 'Sign in to verify your profile and continue.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.submit': 'Sign in',
  'auth.failed': 'We could not sign you in. Check your details and try again.',
  'preferences.language': 'Language',
  'preferences.appearance': 'Appearance',
  'preferences.system': 'System',
  'preferences.light': 'Light',
  'preferences.dark': 'Dark',
  'home.wordmark': 'pomelo.',
  'home.openProfile': 'Open profile',
  'home.streak': '6 days',
  'home.date': 'TUESDAY, AUGUST 11',
  'home.hero.answer.eyebrow': 'POM IS READY',
  'home.hero.answer.title': 'Today you get to\nmake something together.',
  'home.hero.answer.progress': '6 Moments together',
  'home.hero.waiting.eyebrow': 'YOUR PART IS READY',
  'home.hero.waiting.title': 'Waiting for\nLucía.',
  'home.hero.waiting.progress': '6 Moments together',
  'home.hero.ready.eyebrow': 'POM IS EXCITED',
  'home.hero.ready.title': 'You can reveal\nit now.',
  'home.hero.ready.progress': '6 Moments together',
  'home.hero.complete.eyebrow': 'NEW MEMORY',
  'home.hero.complete.title': 'It is now in\nyour History.',
  'home.hero.complete.progress': '7 Moments together',
  'moment.kind.question': 'QUESTION',
  'moment.kind.answered': 'ANSWERED',
  'moment.kind.ready': 'READY',
  'moment.kind.revealed': 'REVEALED',
  'moment.action.answer': 'Answer',
  'moment.action.remind': 'Remind Lucía',
  'moment.action.reveal': 'Reveal the Moment',
  'moment.today': "TODAY'S MOMENT",
  'moment.promptLabel': "TODAY'S QUESTION",
  'moment.prompt': 'What small thing Lucía did made you smile this week?',
  'moment.privacy': "You will answer without seeing each other's response.",
  'moment.partnerPending': 'Lucía has not answered yet',
  'moment.saved': 'Answer saved · waiting for Lucía',
  'moment.you': 'YOU',
  'moment.partner': 'LUCÍA',
  'moment.ownAnswer': '“The coffee you left ready for me.”',
  'moment.partnerLocked': 'Answer ready · still hidden',
  'moment.partnerAnswer': '“When you hugged me and made dinner after a very long day.”',
  'moment.continue': 'Keep talking...',
  'moment.send': 'Send reply',
  'nav.home': 'Home',
  'nav.history': 'History',
  'nav.map': 'Map',
  'nav.pair': 'Pair',
  'widget.title': "Today's Moment",
  'widget.action': 'Open Pomelo',
};

export const catalogs = { es, en } as const;
