export const es = {
  'common.back': 'Volver',
  'common.cancel': 'Cancelar',
  'common.close': 'Cerrar',
  'common.retry': 'Reintentar',
  'common.signOut': 'Cerrar sesión',
  'runtime.loading': 'Preparando vuestro espacio...',
  'runtime.configTitle': 'Pomelo necesita configuración',
  'runtime.configBody': 'Revisa el entorno de desarrollo y vuelve a intentarlo.',
  'runtime.networkTitle': 'No hemos podido conectar',
  'runtime.networkBody': 'Tu sesión sigue segura. Comprueba la conexión y reintenta.',
  'auth.title': 'Volved a vuestro Pomelo',
  'auth.body': 'Inicia sesión para verificar tu perfil y continuar.',
  'auth.email': 'Correo electrónico',
  'auth.password': 'Contraseña',
  'auth.submit': 'Iniciar sesión',
  'auth.failed': 'No hemos podido iniciar sesión. Revisa los datos e inténtalo de nuevo.',
  'preferences.language': 'Idioma',
  'preferences.appearance': 'Apariencia',
  'preferences.system': 'Sistema',
  'preferences.light': 'Claro',
  'preferences.dark': 'Oscuro',
  'home.wordmark': 'pomelo.',
  'home.openProfile': 'Abrir perfil',
  'home.streak': '6 días',
  'home.streak.one': '1 día',
  'home.streak.many': '{count} días',
  'home.date': 'MARTES, 11 DE AGOSTO',
  'home.hero.answer.eyebrow': 'POM ESTÁ LISTO',
  'home.hero.answer.title': 'Hoy os toca\ncrear algo juntos.',
  'home.hero.answer.progress': '6 momentos juntos',
  'home.hero.waiting.eyebrow': 'TU PARTE ESTÁ LISTA',
  'home.hero.waiting.title': 'Tu respuesta está guardada.\nFalta la de tu pareja.',
  'home.hero.waiting.progress': '6 momentos juntos',
  'home.hero.ready.eyebrow': 'POM ESTÁ EMOCIONADO',
  'home.hero.ready.title': 'Ya podéis\ndescubrirlo.',
  'home.hero.ready.progress': '6 momentos juntos',
  'home.hero.complete.eyebrow': 'NUEVO RECUERDO',
  'home.hero.complete.title': 'Ya está en\nvuestra historia.',
  'home.hero.complete.progress': '7 momentos juntos',
  'home.progress.one': '1 momento juntos',
  'home.progress.many': '{count} momentos juntos',
  'home.waiting.date': 'MIENTRAS ESPERAS',
  'home.waiting.eyebrow': 'VUESTRO ESPACIO YA ESTÁ LISTO',
  'home.waiting.title': 'Puedes hacerlo\ntuyo desde hoy.',
  'home.waiting.progress': 'Invitación pendiente',
  'home.waiting.kind': 'LO DE HOY',
  'home.waiting.cardTitle': 'Vuestro primer momento juntos.',
  'home.waiting.cardBody': 'Cuando tu pareja se una, aparecerá aquí vuestra primera propuesta gratuita. Mientras tanto, puedes recorrer Pomelo.',
  'home.waiting.cardAction': 'Ver la invitación',
  'moment.kind.question': 'PREGUNTA',
  'moment.kind.photo': 'FOTO',
  'moment.kind.doodle': 'DIBUJO',
  'moment.kind.answered': 'RESPONDIDO',
  'moment.kind.ready': 'LISTO',
  'moment.kind.revealed': 'REVELADO',
  'moment.kind.recovery': 'RECUPERACIÓN',
  'moment.kind.expired': 'CADUCADO',
  'moment.action.answer': 'Responder',
  'moment.action.remind': 'Avisar a Lucía',
  'moment.action.reveal': 'Descubrirlo juntos',
  'moment.photo.privacy': 'Vuestras fotos siguen ocultas hasta Reveal.',
  'moment.photo.sequence': 'Haced primero la captura trasera y después la frontal. Podéis repetirlas antes de enviar.',
  'moment.photo.rear': 'Cámara trasera',
  'moment.photo.front': 'Cámara frontal',
  'moment.photo.camera': 'Cámara',
  'moment.photo.gallery': 'Galería',
  'moment.photo.submit': 'Enviar mis fotos',
  'moment.photo.saved': 'Tus dos fotos están guardadas.',
  'moment.photo.waiting': 'Tu pareja todavía está preparando su Contribution.',
  'moment.photo.revealed': 'Las fotos ya están reveladas.',
  'moment.photo.revealedBody': 'Vuestra composición ya forma parte de la historia.',
  'moment.photo.error.incomplete': 'Completa la captura trasera y frontal antes de enviar.',
  'moment.doodle.connected': 'Pareja conectada',
  'moment.doodle.reconnecting': 'Reconectando',
  'moment.doodle.sharedCanvas': 'Los dos dibujáis sobre el mismo lienzo. Los trazos de cada persona se distinguen suavemente.',
  'moment.doodle.youFinished': 'Has marcado tu parte como terminada.',
  'moment.doodle.finishPrompt': 'Marca cuando hayas terminado.',
  'moment.doodle.partnerFinished': 'Tu pareja también ha terminado.',
  'moment.doodle.partnerDrawing': 'Tu pareja todavía está dibujando.',
  'moment.doodle.finish': 'He terminado',
  'moment.doodle.syncPending': 'Guardando el lienzo para que podáis continuar.',
  'moment.doodle.revealed': 'Este lienzo ya forma parte de vuestra historia.',
  'moment.today': 'LO DE HOY',
  'moment.promptLabel': 'PREGUNTA DE HOY',
  'moment.prompt': '¿Qué pequeño gesto de Lucía te hizo sonreír esta semana?',
  'moment.privacy': 'Responderéis sin ver la respuesta del otro.',
  'moment.partnerPending': 'Tu pareja aún no ha respondido',
  'moment.saved': 'Respuesta guardada · esperando a tu pareja',
  'moment.you': 'TÚ',
  'moment.partner': 'LUCÍA',
  'moment.ownAnswer': '“El café que me dejaste preparado.”',
  'moment.partnerLocked': 'Respuesta lista · todavía oculta',
  'moment.partnerAnswer': '“Cuando me abrazaste al llegar a casa y preparaste la cena.”',
  'moment.continue': 'Seguid hablando...',
  'moment.send': 'Enviar respuesta',
  'moment.answerLabel': 'Tu respuesta',
  'moment.answerPlaceholder': 'Escribe algo breve...',
  'moment.answerSubmit': 'Guardar mi respuesta',
  'moment.partnerReady': 'Tu pareja ya ha respondido. Su respuesta sigue oculta.',
  'moment.window.normal': 'Ventana normal - quedan {time}',
  'moment.window.recovery': 'Recuperación - quedan {time}',
  'moment.window.expired': 'Este Moment ha caducado.',
  'moment.window.complete': 'Las dos respuestas están guardadas.',
  'moment.expired': 'La ventana terminó. La respuesta guardada no se revela.',
  'moment.syncPending': 'Guardado en este dispositivo. Falta sincronizar la respuesta.',
  'moment.streakRecovery': 'Tenéis una recuperación gratuita para proteger un día perdido.',
  'moment.revealedNote': 'El primer recuerdo ya está en vuestra historia.',
  'moment.loadFailure': 'No hemos podido cargar lo de hoy. Inténtalo de nuevo.',
  'moment.error.invalidResponse': 'Revisa tu respuesta antes de guardarla.',
  'moment.error.draftStorage': 'No hemos podido guardar la respuesta en este dispositivo. Inténtalo de nuevo.',
  'moment.error.momentClosed': 'Este momento ya está cerrado.',
  'moment.error.momentNotReady': 'Aún falta una respuesta para descubrirlo.',
  'moment.error.network': 'No hemos podido conectar. Inténtalo de nuevo.',
  'moment.error.unexpected': 'Algo no ha salido bien. Inténtalo de nuevo.',
  'nav.home': 'Inicio',
  'nav.history': 'Historia',
  'nav.map': 'Mapa',
  'nav.pair': 'Pareja',
  'pair.loading': 'Preparando vuestro espacio...',
  'pair.loadFailure.title': 'No podemos cargar vuestra pareja.',
  'pair.loadFailure.body': 'No asumiremos que no tienes pareja hasta recuperar el estado compartido.',
  'pair.setup.eyebrow': 'VUESTRO ESPACIO PRIVADO',
  'pair.setup.title': 'Empezad vuestra historia.',
  'pair.setup.body': 'Crea una pareja e invita a la otra persona, o únete con el código que te han enviado.',
  'pair.setup.create': 'Crear nuestra pareja',
  'pair.setup.join': 'Tengo una invitación',
  'pair.create.eyebrow': 'CREAR PAREJA',
  'pair.create.title': 'Una fecha para los dos.',
  'pair.create.body': 'Guardaremos vuestro aniversario una sola vez en el espacio compartido.',
  'pair.create.anniversary': 'Vuestro aniversario',
  'pair.create.placeholder': 'AAAA-MM-DD',
  'pair.create.submit': 'Crear e invitar',
  'pair.create.invalid': 'Escribe una fecha real con el formato AAAA-MM-DD.',
  'pair.create.future': 'El aniversario no puede estar en el futuro.',
  'pair.join.eyebrow': 'UNIRME A UNA PAREJA',
  'pair.join.title': 'Introduce vuestro código.',
  'pair.join.body': 'Antes de aceptar verás claramente a qué pareja te estás uniendo.',
  'pair.join.code': 'Código de invitación',
  'pair.join.placeholder': 'ABCD-EF12',
  'pair.join.submit': 'Comprobar invitación',
  'pair.waiting.eyebrow': 'INVITACIÓN PENDIENTE',
  'pair.waiting.title': 'Esperando a tu pareja',
  'pair.waiting.body': 'Comparte el enlace o el código. Solo una persona podrá usar esta invitación.',
  'pair.waiting.code': 'CÓDIGO ALTERNATIVO',
  'pair.waiting.expires': 'La invitación caduca el',
  'pair.waiting.share': 'Reenviar invitación',
  'pair.waiting.cancel': 'Cancelar invitación',
  'pair.waiting.renew': 'Crear una nueva invitación',
  'pair.waiting.cancelTitle': '¿Cancelar esta invitación?',
  'pair.waiting.cancelBody': 'El enlace y el código dejarán de funcionar. Podrás crear otra invitación después.',
  'pair.waiting.cancelConfirm': 'Cancelar invitación',
  'pair.waiting.cancelled': 'Esta invitación está cancelada.',
  'pair.waiting.expired': 'Esta invitación ha caducado.',
  'pair.waiting.unlink': 'Cerrar esta pareja',
  'pair.waiting.unlinkTitle': '¿Cerrar esta pareja?',
  'pair.waiting.unlinkBody': 'La invitación dejará de funcionar y podrás crear otra pareja o unirte a una distinta.',
  'pair.waiting.unlinkConfirm': 'Cerrar pareja',
  'pair.waiting.shareIntro': 'Únete a nuestra pareja privada en Pomelo:',
  'pair.waiting.shareCode': 'Código alternativo',
  'section.history.eyebrow': 'VUESTRA HISTORIA',
  'section.history.title': 'Aquí crecerán vuestros recuerdos.',
  'section.history.waitingBody': 'Vuestra historia empezará cuando tu pareja se una y guardéis vuestro primer recuerdo.',
  'section.history.activeBody': 'Los recuerdos que creéis aparecerán aquí automáticamente, ordenados para volver a ellos cuando queráis.',
  'history.title': 'Vuestra historia crece aquí.',
  'history.body': 'Cada Reveal guarda lo que habéis creado juntos, con la pregunta y las dos respuestas.',
  'history.pom': 'POM REACCIONÓ',
  'history.emptyTitle': 'El primer recuerdo empieza hoy.',
  'history.emptyBody': 'Cuando los dos respondáis y hagáis Reveal, vuestro primer recuerdo aparecerá aquí.',
  'history.homeAction': 'Ir a lo de hoy',
  'history.missingContribution': 'Esta respuesta ya no está disponible.',
  'history.widgetVisible': 'Visible en el widget',
  'history.widgetHidden': 'Oculta para el widget',
  'thread.open': 'Seguid hablando',
  'thread.close': 'Cerrar Thread',
  'thread.title': 'Thread de este recuerdo',
  'thread.placeholder': 'Escribe un mensaje breve...',
  'thread.empty': 'Todavía no hay mensajes en este Thread.',
  'thread.readOnly': 'Este recuerdo está en Archive Mode y se puede leer, pero no editar.',
  'thread.error.empty': 'Escribe algo antes de enviar.',
  'thread.error.tooLong': 'El mensaje es demasiado largo.',
  'thread.error.network': 'No hemos podido enviar el mensaje. Puedes reintentarlo.',
  'thread.error.unexpected': 'No hemos podido abrir este Thread. Inténtalo de nuevo.',
  'section.map.eyebrow': 'VUESTROS LUGARES',
  'section.map.title': 'Un mapa hecho de recuerdos.',
  'section.map.waitingBody': 'Cuando tu pareja se una, los recuerdos con una ciudad compartida empezarán a dibujar vuestro mapa.',
  'section.map.activeBody': 'Los recuerdos con una ciudad compartida aparecerán aquí. Pomelo nunca mostrará vuestra ubicación en directo.',
  'section.waitingStatus': 'ESPERANDO A TU PAREJA',
  'section.emptyStatus': 'TODAVÍA ESTÁ VACÍO',
  'section.manageInvitation': 'Ver la invitación',
  'pair.active.eyebrow': 'PAREJA ACTIVA',
  'pair.active.title': 'Ya estáis juntos.',
  'pair.active.body': 'Este espacio es privado y solo tiene dos miembros.',
  'pair.active.anniversary': 'ANIVERSARIO COMPARTIDO',
  'pair.active.members': 'MIEMBROS',
  'pair.active.openHome': 'Ir a lo de hoy',
  'pair.space.eyebrow': 'ESPACIO DE LA PAREJA',
  'pair.space.title': 'Las fechas que importan.',
  'pair.space.body': 'Cumpleaños, aniversario y planes futuros viven aquí, separados del ritual diario.',
  'pair.space.members': 'FECHAS PERSONALES',
  'pair.space.birthDate': 'Cumpleaños',
  'pair.space.birthDateValue': 'Cumpleaños de {name}: {date}',
  'pair.space.anniversary': 'Aniversario compartido',
  'pair.space.importantDates': 'FECHAS IMPORTANTES',
  'pair.space.next': 'PRÓXIMA FECHA',
  'pair.space.nextBirthday': 'Cumpleaños de {name}',
  'pair.space.nextDateIn': '{date} - En {count} días',
  'pair.space.nextDateToday': '{date} - Hoy',
  'pair.space.today': 'Hoy',
  'pair.space.none': 'Todavía no hay otra fecha guardada.',
  'pair.space.add': 'Añadir fecha',
  'pair.space.edit': 'Editar',
  'pair.space.delete': 'Eliminar',
  'pair.space.deleteTitle': '¿Eliminar esta fecha?',
  'pair.space.deleteBody': 'Desaparecerá de vuestro espacio y de cualquier cuenta atrás.',
  'pair.space.name': 'Nombre',
  'pair.space.kind': 'Tipo',
  'pair.space.trip': 'Viaje',
  'pair.space.custom': 'Personalizada',
  'pair.space.date': 'Fecha futura',
  'pair.space.placeholder': 'AAAA-MM-DD',
  'pair.space.repeat': 'Repetir cada año',
  'pair.space.dateOnce': '{date}',
  'pair.space.dateYearly': '{date} - Repite cada año',
  'pair.space.datePast': '{date} - Archivada',
  'pair.space.save': 'Guardar fecha',
  'pair.space.cancel': 'Cancelar edición',
  'pair.space.past': 'Archivada',
  'pair.active.unlink': 'Desvincular pareja',
  'pair.unlink.title': '¿Desvincular la pareja?',
  'pair.unlink.body': 'Dejarán de aparecer nuevas propuestas. Podréis seguir viendo vuestra historia.',
  'pair.unlink.confirm': 'Desvincular',
  'pair.archive.eyebrow': 'HISTORIA GUARDADA',
  'pair.archive.title': 'Vuestra historia queda guardada.',
  'pair.archive.body': 'La pareja está desvinculada y no aparecerán nuevas propuestas. Podéis seguir viendo vuestra historia.',
  'pair.archive.newPair': 'Crear o unirme a otra pareja',
  'invite.loading': 'Comprobando la invitación...',
  'invite.valid.eyebrow': 'INVITACIÓN PRIVADA',
  'invite.valid.title': 'Te han invitado a una pareja.',
  'invite.valid.body': 'Confirma los datos compartidos antes de unirte. Tu Profile personal ya está completo y no tendrás que repetir el aniversario.',
  'invite.valid.creator': 'TE INVITA',
  'invite.valid.anniversary': 'ANIVERSARIO COMPARTIDO',
  'invite.valid.accept': 'Unirme a esta pareja',
  'invite.success.eyebrow': 'PAREJA ACTIVA',
  'invite.success.title': 'Ya estáis juntos.',
  'invite.success.body': 'La invitación se ha usado una sola vez y vuestro espacio privado está listo.',
  'invite.success.continue': 'Continuar',
  'invite.cancelled.title': 'Invitación cancelada',
  'invite.cancelled.body': 'Pide a tu pareja que cree una invitación nueva.',
  'invite.expired.title': 'Invitación caducada',
  'invite.expired.body': 'El enlace ya no es válido. Tu pareja puede generar otro sin crear una pareja nueva.',
  'invite.invalid.title': 'No encontramos esta invitación',
  'invite.invalid.body': 'Revisa el enlace o vuelve a escribir el código.',
  'invite.used.title': 'Invitación ya utilizada',
  'invite.used.body': 'Este enlace era de un solo uso. Si ya te uniste, inicia sesión con la cuenta correcta.',
  'invite.pairFull.title': 'Esta pareja ya está completa',
  'invite.pairFull.body': 'Pomelo mantiene cada pareja privada con exactamente dos miembros.',
  'invite.tryCode': 'Probar otro código',
  'pair.error.alreadyPaired': 'Ya perteneces a una pareja activa.',
  'pair.error.configuration': 'Este entorno todavía no tiene configurado el backend.',
  'pair.error.invitationCancelled': 'La invitación fue cancelada. Pide una nueva.',
  'pair.error.invitationExpired': 'La invitación ha caducado. Pide una nueva.',
  'pair.error.invitationInvalid': 'No encontramos esa invitación.',
  'pair.error.invitationUsed': 'Esta invitación ya se ha utilizado.',
  'pair.error.invalidAnniversary': 'Revisa la fecha del aniversario.',
  'pair.error.invalidImportantDate': 'Escribe un nombre y una fecha futura válida.',
  'pair.error.invalidImportantDate.name': 'Escribe un nombre para esta fecha.',
  'pair.error.invalidImportantDate.date': 'Escribe una fecha válida con el formato AAAA-MM-DD.',
  'pair.error.invalidImportantDate.future': 'Elige una fecha futura.',
  'pair.error.invalidImportantDate.kind': 'Elige un tipo de fecha válido.',
  'pair.error.invalidImportantDate.recurrence': 'Elige una repetición válida.',
  'pair.error.importantDateNotFound': 'Esta fecha ya no está disponible.',
  'pair.error.network': 'No hemos podido conectar. Inténtalo de nuevo.',
  'pair.error.notAllowed': 'No puedes realizar esta acción en esta pareja.',
  'pair.error.pairFull': 'Esta pareja ya tiene dos miembros.',
  'pair.error.profileIncomplete': 'Completa tu Profile personal antes de continuar.',
  'pair.error.unexpected': 'Algo no ha salido bien. Inténtalo de nuevo.',
  'premium.eyebrow': 'PREMIUM PARA LOS DOS',
  'premium.title': 'Momentos juntos.\nConexión real.',
  'premium.subtitle': 'Un plan. Ambos incluidos.',
  'premium.body': 'Todo lo que necesitáis para seguir creando vuestra historia juntos.',
  'premium.cta': 'Desbloquear Pomelo para los dos',
  'premium.annual': 'Anual',
  'premium.monthly': 'Mensual',
  'premium.recommended': 'MEJOR VALOR',
  'premium.features.eyebrow': 'CON PREMIUM',
  'premium.feature.moments': 'Seguid creando momentos juntos',
  'premium.feature.map': 'Descubrid el mapa de vuestra historia',
  'premium.feature.widget': 'Llevad vuestra historia a la pantalla de inicio',
  'premium.perPersonMonth': '{price} / persona / mes',
  'premium.save': 'AHORRA {percent}%',
  'premium.price.unavailable': 'Precio no disponible',
  'premium.billing.annual': '{price} cada año',
  'premium.billing.monthly': '{price} cada mes',
  'premium.renewal': 'Se renueva automáticamente. Puedes cancelar cuando quieras desde la tienda.',
  'premium.cancelled': 'Premium seguirá activo hasta {date}. Después, seguiréis viendo vuestro primer recuerdo y vuestra historia, pero no podréis crear nuevos momentos.',
  'premium.gracePeriod': 'Hay un problema con el cobro. Premium seguirá activo hasta {date} mientras se resuelve.',
  'premium.expired': 'Premium ha caducado. Vuestro primer recuerdo sigue guardado y podéis volver a verlo cuando queráis.',
  'premium.noTrial': 'Sin prueba gratuita, producto semanal ni ofertas sorpresa.',
  'premium.restore': 'Restaurar compra',
  'premium.terms': 'Términos de uso',
  'premium.privacy': 'Privacidad',
  'premium.purchaseSync': 'Compra recibida. Estamos activando Premium para los dos.',
  'premium.unlock': 'Desbloquear Premium',
  'premium.next.eyebrow': 'ACCESO GRATUITO COMPLETADO',
  'premium.next.title': 'Desbloquea vuestro siguiente momento',
  'premium.next.body': 'Este primer recuerdo es vuestro. Para seguir creando un momento nuevo cada día, activad Premium para los dos.',
  'premium.next.cta': 'Ver Premium',
  'premium.next.syncEyebrow': 'COMPRA RECIBIDA',
  'premium.next.syncTitle': 'Estamos activando Premium',
  'premium.next.syncBody': 'La tienda ha confirmado la compra. Premium se activará automáticamente para los dos.',
  'premium.next.syncCta': 'Activando Premium...',
  'premium.locked.eyebrow': 'DISPONIBLE CON PREMIUM',
  'premium.locked.body': 'Activad Premium para los dos para usar esta función.',
  'premium.map.title': 'El mapa de vuestra historia',
  'premium.map.body': 'Con Premium para los dos podréis ver los lugares que forman vuestra historia.',
  'premium.widget.title': 'Widget de Pomelo',
  'premium.widget.body': 'Vuestra historia siempre a mano desde la pantalla de inicio.',
  'premium.error.configuration': 'Premium todavía no está configurado en este entorno.',
  'premium.error.network': 'No hemos podido comprobar Premium. Inténtalo de nuevo.',
  'premium.error.purchaseNotActivated': 'La compra se ha completado, pero este plan no ha activado el entitlement Premium. Revisa la configuración de RevenueCat.',
  'premium.error.unavailable': 'Ahora mismo no hay planes disponibles. Inténtalo de nuevo más tarde.',
  'premium.error.unexpected': 'Algo no ha salido bien. Inténtalo de nuevo.',
  'widget.title': 'Lo de hoy',
  'widget.action': 'Abrir Pomelo',
} as const;

export type TranslationKey = keyof typeof es;

export const en: Record<TranslationKey, string> = {
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.retry': 'Try again',
  'common.signOut': 'Sign out',
  'runtime.loading': 'Preparing your shared space...',
  'runtime.configTitle': 'Pomelo needs configuration',
  'runtime.configBody': 'Check the development environment and try again.',
  'runtime.networkTitle': 'We could not connect',
  'runtime.networkBody': 'Your session is safe. Check your connection and try again.',
  'auth.title': 'Come back to your Pomelo',
  'auth.body': 'Sign in to verify your profile and continue.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.submit': 'Sign in',
  'auth.failed': 'We could not sign you in. Check your details and try again.',
  'preferences.language': 'Language',
  'preferences.appearance': 'Appearance',
  'preferences.system': 'System',
  'preferences.light': 'Light',
  'preferences.dark': 'Dark',
  'home.wordmark': 'pomelo.',
  'home.openProfile': 'Open profile',
  'home.streak': '6 days',
  'home.streak.one': '1 day',
  'home.streak.many': '{count} days',
  'home.date': 'TUESDAY, AUGUST 11',
  'home.hero.answer.eyebrow': 'POM IS READY',
  'home.hero.answer.title': 'Today you get to\nmake something together.',
  'home.hero.answer.progress': '6 moments together',
  'home.hero.waiting.eyebrow': 'YOUR PART IS READY',
  'home.hero.waiting.title': 'Your answer is saved.\nYour partner is next.',
  'home.hero.waiting.progress': '6 moments together',
  'home.hero.ready.eyebrow': 'POM IS EXCITED',
  'home.hero.ready.title': 'You can reveal\nit now.',
  'home.hero.ready.progress': '6 moments together',
  'home.hero.complete.eyebrow': 'NEW MOMENT',
  'home.hero.complete.title': 'It is now in\nyour History.',
  'home.hero.complete.progress': '7 moments together',
  'home.progress.one': '1 moment together',
  'home.progress.many': '{count} moments together',
  'home.waiting.date': 'WHILE YOU WAIT',
  'home.waiting.eyebrow': 'YOUR SHARED SPACE IS READY',
  'home.waiting.title': 'Make it yours\nfrom day one.',
  'home.waiting.progress': 'Invitation pending',
  'home.waiting.kind': 'TODAY IN POMELO',
  'home.waiting.cardTitle': 'Your first moment together.',
  'home.waiting.cardBody': 'Your first shared prompt will appear here when your partner joins. In the meantime, you can look around Pomelo.',
  'home.waiting.cardAction': 'View the Invitation',
  'moment.kind.question': 'QUESTION',
  'moment.kind.photo': 'PHOTO',
  'moment.kind.doodle': 'DOODLE',
  'moment.kind.answered': 'ANSWERED',
  'moment.kind.ready': 'READY',
  'moment.kind.revealed': 'REVEALED',
  'moment.kind.recovery': 'RECOVERY',
  'moment.kind.expired': 'EXPIRED',
  'moment.action.answer': 'Answer',
  'moment.action.remind': 'Remind Lucía',
  'moment.action.reveal': 'Reveal it together',
  'moment.photo.privacy': 'Your photos stay hidden until Reveal.',
  'moment.photo.sequence': 'Take the rear capture first, then the front one. You can retake either before sending.',
  'moment.photo.rear': 'Rear camera',
  'moment.photo.front': 'Front camera',
  'moment.photo.camera': 'Camera',
  'moment.photo.gallery': 'Gallery',
  'moment.photo.submit': 'Send my photos',
  'moment.photo.saved': 'Both photos are saved.',
  'moment.photo.waiting': 'Your partner is still preparing their Contribution.',
  'moment.photo.revealed': 'The photos are revealed.',
  'moment.photo.revealedBody': 'Your composition is now part of History.',
  'moment.photo.error.incomplete': 'Complete both the rear and front capture before sending.',
  'moment.doodle.connected': 'Partner connected',
  'moment.doodle.reconnecting': 'Reconnecting',
  'moment.doodle.sharedCanvas': 'You are both drawing on the same canvas. Each person\'s strokes are gently distinct.',
  'moment.doodle.youFinished': 'You marked your part as finished.',
  'moment.doodle.finishPrompt': 'Mark it when you are finished.',
  'moment.doodle.partnerFinished': 'Your partner is finished too.',
  'moment.doodle.partnerDrawing': 'Your partner is still drawing.',
  'moment.doodle.finish': 'I\'m finished',
  'moment.doodle.syncPending': 'Saving the canvas so you can continue together.',
  'moment.doodle.revealed': 'This canvas is now part of your History.',
  'moment.today': 'TODAY IN POMELO',
  'moment.promptLabel': "TODAY'S QUESTION",
  'moment.prompt': 'What small thing Lucía did made you smile this week?',
  'moment.privacy': "You will answer without seeing each other's response.",
  'moment.partnerPending': 'Your partner has not answered yet',
  'moment.saved': 'Answer saved · waiting for your partner',
  'moment.you': 'YOU',
  'moment.partner': 'LUCÍA',
  'moment.ownAnswer': '“The coffee you left ready for me.”',
  'moment.partnerLocked': 'Answer ready · still hidden',
  'moment.partnerAnswer': '“When you hugged me and made dinner after a very long day.”',
  'moment.continue': 'Keep talking...',
  'moment.send': 'Send reply',
  'moment.answerLabel': 'Your answer',
  'moment.answerPlaceholder': 'Write something brief...',
  'moment.answerSubmit': 'Save my answer',
  'moment.partnerReady': 'Your partner has answered. Their response is still hidden.',
  'moment.window.normal': 'Normal window - {time} left',
  'moment.window.recovery': 'Recovery - {time} left',
  'moment.window.expired': 'This Moment has expired.',
  'moment.window.complete': 'Both answers are saved.',
  'moment.expired': 'The window ended. The saved response stays private.',
  'moment.syncPending': 'Saved on this device. Your response still needs to sync.',
  'moment.streakRecovery': 'You have one free recovery to protect a missed day.',
  'moment.revealedNote': 'Your first moment is now in your History.',
  'moment.loadFailure': 'We could not load today\'s Moment. Try again.',
  'moment.error.invalidResponse': 'Check your answer before saving it.',
  'moment.error.draftStorage': 'We could not save the response on this device. Try again.',
  'moment.error.momentClosed': 'This Moment is already closed.',
  'moment.error.momentNotReady': 'One answer is still missing before Reveal.',
  'moment.error.network': 'We could not connect. Try again.',
  'moment.error.unexpected': 'Something went wrong. Try again.',
  'nav.home': 'Home',
  'nav.history': 'History',
  'nav.map': 'Map',
  'nav.pair': 'Pair',
  'pair.loading': 'Preparing your shared space...',
  'pair.loadFailure.title': 'We cannot load your Pair.',
  'pair.loadFailure.body': 'We will not assume you have no Pair until the shared state is available again.',
  'pair.setup.eyebrow': 'YOUR PRIVATE SPACE',
  'pair.setup.title': 'Start your story.',
  'pair.setup.body': 'Create a Pair and invite the other person, or join with the code they sent you.',
  'pair.setup.create': 'Create our Pair',
  'pair.setup.join': 'I have an Invitation',
  'pair.create.eyebrow': 'CREATE A PAIR',
  'pair.create.title': 'One date for both of you.',
  'pair.create.body': 'Your anniversary is stored once in your shared space.',
  'pair.create.anniversary': 'Your anniversary',
  'pair.create.placeholder': 'YYYY-MM-DD',
  'pair.create.submit': 'Create and invite',
  'pair.create.invalid': 'Enter a real date using YYYY-MM-DD.',
  'pair.create.future': 'The anniversary cannot be in the future.',
  'pair.join.eyebrow': 'JOIN A PAIR',
  'pair.join.title': 'Enter your shared code.',
  'pair.join.body': 'You will clearly see which Pair you are joining before accepting.',
  'pair.join.code': 'Invitation code',
  'pair.join.placeholder': 'ABCD-EF12',
  'pair.join.submit': 'Check Invitation',
  'pair.waiting.eyebrow': 'PENDING INVITATION',
  'pair.waiting.title': 'Waiting for your partner',
  'pair.waiting.body': 'Share the link or code. Only one person can use this Invitation.',
  'pair.waiting.code': 'ALTERNATIVE CODE',
  'pair.waiting.expires': 'The Invitation expires on',
  'pair.waiting.share': 'Share Invitation again',
  'pair.waiting.cancel': 'Cancel Invitation',
  'pair.waiting.renew': 'Create a new Invitation',
  'pair.waiting.cancelTitle': 'Cancel this Invitation?',
  'pair.waiting.cancelBody': 'The link and code will stop working. You can create another Invitation afterward.',
  'pair.waiting.cancelConfirm': 'Cancel Invitation',
  'pair.waiting.cancelled': 'This Invitation has been cancelled.',
  'pair.waiting.expired': 'This Invitation has expired.',
  'pair.waiting.unlink': 'Close this Pair',
  'pair.waiting.unlinkTitle': 'Close this Pair?',
  'pair.waiting.unlinkBody': 'The Invitation will stop working, and you can create or join a different Pair.',
  'pair.waiting.unlinkConfirm': 'Close Pair',
  'pair.waiting.shareIntro': 'Join our private Pair in Pomelo:',
  'pair.waiting.shareCode': 'Alternative code',
  'section.history.eyebrow': 'YOUR HISTORY',
  'section.history.title': 'This is where your shared moments will grow.',
  'section.history.waitingBody': 'Your History will begin when your partner joins and you save your first moment together.',
  'section.history.activeBody': 'Every moment you create will appear here automatically, ready for you to revisit.',
  'history.title': 'Your History grows here.',
  'history.body': 'Every Reveal saves what you created together, with the prompt and both answers.',
  'history.pom': 'POM REACTED',
  'history.emptyTitle': 'Your first moment starts today.',
  'history.emptyBody': 'When you both answer and Reveal, your first moment will appear here.',
  'history.homeAction': 'Go to today',
  'history.missingContribution': 'This answer is no longer available.',
  'history.widgetVisible': 'Visible in widget',
  'history.widgetHidden': 'Hidden from widget',
  'thread.open': 'Keep talking',
  'thread.close': 'Close Thread',
  'thread.title': 'Thread for this Memory',
  'thread.placeholder': 'Write a short message...',
  'thread.empty': 'There are no messages in this Thread yet.',
  'thread.readOnly': 'This Memory is in Archive Mode. You can read it, but not edit it.',
  'thread.error.empty': 'Write something before sending.',
  'thread.error.tooLong': 'That message is too long.',
  'thread.error.network': 'We could not send the message. You can retry it.',
  'thread.error.unexpected': 'We could not open this Thread. Try again.',
  'section.map.eyebrow': 'YOUR PLACES',
  'section.map.title': 'A map made from your story.',
  'section.map.waitingBody': 'Once your partner joins, moments with a shared city will begin drawing your map.',
  'section.map.activeBody': 'Moments with a shared city will appear here. Pomelo will never show your live location.',
  'section.waitingStatus': 'WAITING FOR YOUR PARTNER',
  'section.emptyStatus': 'NOTHING HERE YET',
  'section.manageInvitation': 'View the Invitation',
  'pair.active.eyebrow': 'ACTIVE PAIR',
  'pair.active.title': 'You are together.',
  'pair.active.body': 'This space is private and has only two members.',
  'pair.active.anniversary': 'SHARED ANNIVERSARY',
  'pair.active.members': 'MEMBERS',
  'pair.active.openHome': 'Go to today',
  'pair.space.eyebrow': 'PAIR SPACE',
  'pair.space.title': 'The dates that matter.',
  'pair.space.body': 'Birthdays, your anniversary, and future plans live here, apart from the daily ritual.',
  'pair.space.members': 'PERSONAL DATES',
  'pair.space.birthDate': 'Birthday',
  'pair.space.birthDateValue': '{name} birthday: {date}',
  'pair.space.anniversary': 'Shared anniversary',
  'pair.space.importantDates': 'IMPORTANT DATES',
  'pair.space.next': 'NEXT DATE',
  'pair.space.nextBirthday': '{name} birthday',
  'pair.space.nextDateIn': '{date} - In {count} days',
  'pair.space.nextDateToday': '{date} - Today',
  'pair.space.today': 'Today',
  'pair.space.none': 'There are no other saved dates yet.',
  'pair.space.add': 'Add a date',
  'pair.space.edit': 'Edit',
  'pair.space.delete': 'Delete',
  'pair.space.deleteTitle': 'Delete this date?',
  'pair.space.deleteBody': 'It will disappear from your Pair space and any countdown.',
  'pair.space.name': 'Name',
  'pair.space.kind': 'Type',
  'pair.space.trip': 'Trip',
  'pair.space.custom': 'Custom',
  'pair.space.date': 'Future date',
  'pair.space.placeholder': 'YYYY-MM-DD',
  'pair.space.repeat': 'Repeat every year',
  'pair.space.dateOnce': '{date}',
  'pair.space.dateYearly': '{date} - Repeats every year',
  'pair.space.datePast': '{date} - Archived',
  'pair.space.save': 'Save date',
  'pair.space.cancel': 'Cancel editing',
  'pair.space.past': 'Archived',
  'pair.active.unlink': 'Unlink Pair',
  'pair.unlink.title': 'Unlink this Pair?',
  'pair.unlink.body': 'New shared prompts will stop. You can still view your History.',
  'pair.unlink.confirm': 'Unlink',
  'pair.archive.eyebrow': 'SAVED HISTORY',
  'pair.archive.title': 'Your story is still here.',
  'pair.archive.body': 'The Pair is unlinked and no new shared prompts will appear. You can still view your History.',
  'pair.archive.newPair': 'Create or join another Pair',
  'invite.loading': 'Checking the Invitation...',
  'invite.valid.eyebrow': 'PRIVATE INVITATION',
  'invite.valid.title': 'You have been invited to a Pair.',
  'invite.valid.body': 'Confirm the shared details before joining. Your personal Profile is already complete, so you will not enter the anniversary again.',
  'invite.valid.creator': 'INVITED BY',
  'invite.valid.anniversary': 'SHARED ANNIVERSARY',
  'invite.valid.accept': 'Join this Pair',
  'invite.success.eyebrow': 'ACTIVE PAIR',
  'invite.success.title': 'You are together.',
  'invite.success.body': 'The Invitation was used once and your private space is ready.',
  'invite.success.continue': 'Continue',
  'invite.cancelled.title': 'Invitation cancelled',
  'invite.cancelled.body': 'Ask your partner to create a new Invitation.',
  'invite.expired.title': 'Invitation expired',
  'invite.expired.body': 'The link is no longer valid. Your partner can generate another without creating a new Pair.',
  'invite.invalid.title': 'We could not find this Invitation',
  'invite.invalid.body': 'Check the link or enter the code again.',
  'invite.used.title': 'Invitation already used',
  'invite.used.body': 'This was a single-use link. If you already joined, sign in with the correct account.',
  'invite.pairFull.title': 'This Pair is already full',
  'invite.pairFull.body': 'Pomelo keeps every Pair private with exactly two members.',
  'invite.tryCode': 'Try another code',
  'pair.error.alreadyPaired': 'You already belong to an active Pair.',
  'pair.error.configuration': 'The backend is not configured in this environment yet.',
  'pair.error.invitationCancelled': 'The Invitation was cancelled. Ask for a new one.',
  'pair.error.invitationExpired': 'The Invitation has expired. Ask for a new one.',
  'pair.error.invitationInvalid': 'We could not find that Invitation.',
  'pair.error.invitationUsed': 'This Invitation has already been used.',
  'pair.error.invalidAnniversary': 'Check the anniversary date.',
  'pair.error.invalidImportantDate': 'Enter a name and a valid future date.',
  'pair.error.invalidImportantDate.name': 'Enter a name for this date.',
  'pair.error.invalidImportantDate.date': 'Enter a valid date using YYYY-MM-DD.',
  'pair.error.invalidImportantDate.future': 'Choose a future date.',
  'pair.error.invalidImportantDate.kind': 'Choose a valid date type.',
  'pair.error.invalidImportantDate.recurrence': 'Choose a valid recurrence.',
  'pair.error.importantDateNotFound': 'This date is no longer available.',
  'pair.error.network': 'We could not connect. Try again.',
  'pair.error.notAllowed': 'You cannot perform this action for this Pair.',
  'pair.error.pairFull': 'This Pair already has two members.',
  'pair.error.profileIncomplete': 'Complete your personal Profile before continuing.',
  'pair.error.unexpected': 'Something went wrong. Try again.',
  'premium.eyebrow': 'PREMIUM FOR BOTH OF YOU',
  'premium.title': 'Shared moments.\nReal connection.',
  'premium.subtitle': 'One plan. Both included.',
  'premium.body': 'Everything you need to keep building your story together.',
  'premium.cta': 'Unlock Pomelo for both of you',
  'premium.annual': 'Annual',
  'premium.monthly': 'Monthly',
  'premium.recommended': 'BEST VALUE',
  'premium.features.eyebrow': 'WITH PREMIUM',
  'premium.feature.moments': 'Keep creating moments together',
  'premium.feature.map': 'Discover your shared story map',
  'premium.feature.widget': 'Keep your story close on your home screen',
  'premium.perPersonMonth': '{price} / person / month',
  'premium.save': 'SAVE {percent}%',
  'premium.price.unavailable': 'Price unavailable',
  'premium.billing.annual': '{price} every year',
  'premium.billing.monthly': '{price} every month',
  'premium.renewal': 'Renews automatically. Cancel any time from the store.',
  'premium.cancelled': 'Premium stays active until {date}. After that, you can still view your first moment and your History, but you cannot create new moments.',
  'premium.gracePeriod': 'There is a billing issue. Premium stays active until {date} while it is resolved.',
  'premium.expired': 'Premium has expired. Your first moment is still saved and ready to revisit.',
  'premium.noTrial': 'No free trial, weekly product, or surprise offers.',
  'premium.restore': 'Restore purchase',
  'premium.terms': 'Terms of use',
  'premium.privacy': 'Privacy',
  'premium.purchaseSync': 'Purchase received. We are activating Premium for both of you.',
  'premium.unlock': 'Unlock Premium',
  'premium.next.eyebrow': 'FREE ACCESS COMPLETE',
  'premium.next.title': 'Unlock your next moment',
  'premium.next.body': 'Your first Memory is yours to keep. Activate Premium for both of you to create a new moment every day.',
  'premium.next.cta': 'See Premium',
  'premium.next.syncEyebrow': 'PURCHASE RECEIVED',
  'premium.next.syncTitle': 'We are activating Premium',
  'premium.next.syncBody': 'The store confirmed your purchase. Premium will activate automatically for both of you.',
  'premium.next.syncCta': 'Activating Premium...',
  'premium.locked.eyebrow': 'AVAILABLE WITH PREMIUM',
  'premium.locked.body': 'Activate Premium for both of you to use this feature.',
  'premium.map.title': 'Your story map',
  'premium.map.body': 'Premium for both of you unlocks the places that make up your story.',
  'premium.widget.title': 'Pomelo widget',
  'premium.widget.body': 'Keep your story close from the home screen.',
  'premium.error.configuration': 'Premium is not configured in this environment yet.',
  'premium.error.network': 'We could not check Premium. Try again.',
  'premium.error.purchaseNotActivated': 'The purchase completed, but this plan did not activate the Premium entitlement. Check the RevenueCat configuration.',
  'premium.error.unavailable': 'No plans are available right now. Try again later.',
  'premium.error.unexpected': 'Something went wrong. Try again.',
  'widget.title': 'Today in Pomelo',
  'widget.action': 'Open Pomelo',
};

export const catalogs = { es, en } as const;
