export const es = {
  'common.back': 'Volver',
  'common.cancel': 'Cancelar',
  'common.retry': 'Reintentar',
  'common.signOut': 'Cerrar sesión',
  'runtime.loading': 'Preparando vuestro espacio...',
  'runtime.configTitle': 'Pomelo necesita configuración',
  'runtime.configBody': 'Revisa el entorno de desarrollo y vuelve a intentarlo.',
  'runtime.networkTitle': 'No hemos podido conectar',
  'runtime.networkBody': 'Tu sesión sigue segura. Comprueba la conexión y reintenta.',
  'auth.title': 'Volved a vuestro Pomelo',
  'auth.body': 'Inicia sesión para verificar tu perfil y continuar.',
  'auth.email': 'Correo electrónico',
  'auth.password': 'Contraseña',
  'auth.submit': 'Iniciar sesión',
  'auth.failed': 'No hemos podido iniciar sesión. Revisa los datos e inténtalo de nuevo.',
  'preferences.language': 'Idioma',
  'preferences.appearance': 'Apariencia',
  'preferences.system': 'Sistema',
  'preferences.light': 'Claro',
  'preferences.dark': 'Oscuro',
  'home.wordmark': 'pomelo.',
  'home.openProfile': 'Abrir perfil',
  'home.streak': '6 días',
  'home.date': 'MARTES, 11 DE AGOSTO',
  'home.hero.answer.eyebrow': 'POM ESTÁ LISTO',
  'home.hero.answer.title': 'Hoy os toca\ncrear algo juntos.',
  'home.hero.answer.progress': '6 momentos juntos',
  'home.hero.waiting.eyebrow': 'TU PARTE ESTÁ LISTA',
  'home.hero.waiting.title': 'Esperando a\nLucía.',
  'home.hero.waiting.progress': '6 momentos juntos',
  'home.hero.ready.eyebrow': 'POM ESTÁ EMOCIONADO',
  'home.hero.ready.title': 'Ya podéis\ndescubrirlo.',
  'home.hero.ready.progress': '6 momentos juntos',
  'home.hero.complete.eyebrow': 'NUEVO RECUERDO',
  'home.hero.complete.title': 'Ya está en\nvuestra historia.',
  'home.hero.complete.progress': '7 momentos juntos',
  'moment.kind.question': 'PREGUNTA',
  'moment.kind.answered': 'RESPONDIDO',
  'moment.kind.ready': 'LISTO',
  'moment.kind.revealed': 'REVELADO',
  'moment.action.answer': 'Responder',
  'moment.action.remind': 'Avisar a Lucía',
  'moment.action.reveal': 'Descubrir el Momento',
  'moment.today': 'MOMENTO DE HOY',
  'moment.promptLabel': 'PREGUNTA DE HOY',
  'moment.prompt': '¿Qué pequeño gesto de Lucía te hizo sonreír esta semana?',
  'moment.privacy': 'Responderéis sin ver la respuesta del otro.',
  'moment.partnerPending': 'Lucía aún no ha respondido',
  'moment.saved': 'Respuesta guardada · esperando a Lucía',
  'moment.you': 'TÚ',
  'moment.partner': 'LUCÍA',
  'moment.ownAnswer': '“El café que me dejaste preparado.”',
  'moment.partnerLocked': 'Respuesta lista · todavía oculta',
  'moment.partnerAnswer': '“Cuando me abrazaste al llegar a casa y preparaste la cena.”',
  'moment.continue': 'Seguid hablando...',
  'moment.send': 'Enviar respuesta',
  'nav.home': 'Inicio',
  'nav.history': 'Historia',
  'nav.map': 'Mapa',
  'nav.pair': 'Pareja',
  'pair.loading': 'Preparando vuestro espacio...',
  'pair.setup.eyebrow': 'VUESTRO ESPACIO PRIVADO',
  'pair.setup.title': 'Empezad vuestra historia.',
  'pair.setup.body': 'Crea una pareja e invita a la otra persona, o únete con el código que te han enviado.',
  'pair.setup.create': 'Crear nuestra pareja',
  'pair.setup.join': 'Tengo una invitación',
  'pair.create.eyebrow': 'CREAR PAREJA',
  'pair.create.title': 'Una fecha para los dos.',
  'pair.create.body': 'Guardaremos vuestro aniversario una sola vez en el espacio compartido.',
  'pair.create.anniversary': 'Vuestro aniversario',
  'pair.create.placeholder': 'AAAA-MM-DD',
  'pair.create.submit': 'Crear e invitar',
  'pair.create.invalid': 'Escribe una fecha real con el formato AAAA-MM-DD.',
  'pair.create.future': 'El aniversario no puede estar en el futuro.',
  'pair.join.eyebrow': 'UNIRME A UNA PAREJA',
  'pair.join.title': 'Introduce vuestro código.',
  'pair.join.body': 'Antes de aceptar verás claramente a qué pareja te estás uniendo.',
  'pair.join.code': 'Código de invitación',
  'pair.join.placeholder': 'ABCD-EF12',
  'pair.join.submit': 'Comprobar invitación',
  'pair.waiting.eyebrow': 'INVITACIÓN PENDIENTE',
  'pair.waiting.title': 'Esperando a tu pareja',
  'pair.waiting.body': 'Comparte el enlace o el código. Solo una persona podrá usar esta invitación.',
  'pair.waiting.code': 'CÓDIGO ALTERNATIVO',
  'pair.waiting.expires': 'La invitación caduca el',
  'pair.waiting.share': 'Reenviar invitación',
  'pair.waiting.cancel': 'Cancelar invitación',
  'pair.waiting.renew': 'Crear una nueva invitación',
  'pair.waiting.cancelTitle': '¿Cancelar esta invitación?',
  'pair.waiting.cancelBody': 'El enlace y el código dejarán de funcionar. Podrás crear otra invitación después.',
  'pair.waiting.cancelConfirm': 'Cancelar invitación',
  'pair.waiting.cancelled': 'Esta invitación está cancelada.',
  'pair.waiting.expired': 'Esta invitación ha caducado.',
  'pair.waiting.shareIntro': 'Únete a nuestra pareja privada en Pomelo:',
  'pair.waiting.shareCode': 'Código alternativo',
  'pair.active.eyebrow': 'PAREJA ACTIVA',
  'pair.active.title': 'Ya estáis juntos.',
  'pair.active.body': 'Este espacio es privado y solo tiene dos miembros.',
  'pair.active.anniversary': 'ANIVERSARIO COMPARTIDO',
  'pair.active.members': 'MIEMBROS',
  'pair.active.openHome': 'Ir al Momento de hoy',
  'pair.active.unlink': 'Desvincular pareja',
  'pair.unlink.title': '¿Desvincular la pareja?',
  'pair.unlink.body': 'Dejarán de generarse nuevos Moments. El contenido permitido seguirá disponible en Archive Mode.',
  'pair.unlink.confirm': 'Desvincular',
  'pair.archive.eyebrow': 'ARCHIVE MODE',
  'pair.archive.title': 'Vuestra historia queda guardada.',
  'pair.archive.body': 'La pareja está desvinculada y no se generarán nuevos Moments. El contenido permitido seguirá disponible en modo lectura.',
  'invite.loading': 'Comprobando la invitación...',
  'invite.valid.eyebrow': 'INVITACIÓN PRIVADA',
  'invite.valid.title': 'Te han invitado a una pareja.',
  'invite.valid.body': 'Confirma los datos compartidos antes de unirte. Tu Profile personal ya está completo y no tendrás que repetir el aniversario.',
  'invite.valid.creator': 'TE INVITA',
  'invite.valid.anniversary': 'ANIVERSARIO COMPARTIDO',
  'invite.valid.accept': 'Unirme a esta pareja',
  'invite.success.eyebrow': 'PAREJA ACTIVA',
  'invite.success.title': 'Ya estáis juntos.',
  'invite.success.body': 'La invitación se ha usado una sola vez y vuestro espacio privado está listo.',
  'invite.success.continue': 'Continuar',
  'invite.cancelled.title': 'Invitación cancelada',
  'invite.cancelled.body': 'Pide a tu pareja que cree una invitación nueva.',
  'invite.expired.title': 'Invitación caducada',
  'invite.expired.body': 'El enlace ya no es válido. Tu pareja puede generar otro sin crear una pareja nueva.',
  'invite.invalid.title': 'No encontramos esta invitación',
  'invite.invalid.body': 'Revisa el enlace o vuelve a escribir el código.',
  'invite.used.title': 'Invitación ya utilizada',
  'invite.used.body': 'Este enlace era de un solo uso. Si ya te uniste, inicia sesión con la cuenta correcta.',
  'invite.pairFull.title': 'Esta pareja ya está completa',
  'invite.pairFull.body': 'Pomelo mantiene cada pareja privada con exactamente dos miembros.',
  'invite.tryCode': 'Probar otro código',
  'pair.error.alreadyPaired': 'Ya perteneces a una pareja activa.',
  'pair.error.configuration': 'Este entorno todavía no tiene configurado el backend.',
  'pair.error.invitationCancelled': 'La invitación fue cancelada. Pide una nueva.',
  'pair.error.invitationExpired': 'La invitación ha caducado. Pide una nueva.',
  'pair.error.invitationInvalid': 'No encontramos esa invitación.',
  'pair.error.invitationUsed': 'Esta invitación ya se ha utilizado.',
  'pair.error.invalidAnniversary': 'Revisa la fecha del aniversario.',
  'pair.error.network': 'No hemos podido conectar. Inténtalo de nuevo.',
  'pair.error.notAllowed': 'No puedes realizar esta acción en esta pareja.',
  'pair.error.pairFull': 'Esta pareja ya tiene dos miembros.',
  'pair.error.profileIncomplete': 'Completa tu Profile personal antes de continuar.',
  'pair.error.unexpected': 'Algo no ha salido bien. Inténtalo de nuevo.',
  'widget.title': 'Momento de hoy',
  'widget.action': 'Abrir Pomelo',
} as const;

export type TranslationKey = keyof typeof es;

export const en: Record<TranslationKey, string> = {
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.retry': 'Try again',
  'common.signOut': 'Sign out',
  'runtime.loading': 'Preparing your shared space...',
  'runtime.configTitle': 'Pomelo needs configuration',
  'runtime.configBody': 'Check the development environment and try again.',
  'runtime.networkTitle': 'We could not connect',
  'runtime.networkBody': 'Your session is safe. Check your connection and try again.',
  'auth.title': 'Come back to your Pomelo',
  'auth.body': 'Sign in to verify your profile and continue.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.submit': 'Sign in',
  'auth.failed': 'We could not sign you in. Check your details and try again.',
  'preferences.language': 'Language',
  'preferences.appearance': 'Appearance',
  'preferences.system': 'System',
  'preferences.light': 'Light',
  'preferences.dark': 'Dark',
  'home.wordmark': 'pomelo.',
  'home.openProfile': 'Open profile',
  'home.streak': '6 days',
  'home.date': 'TUESDAY, AUGUST 11',
  'home.hero.answer.eyebrow': 'POM IS READY',
  'home.hero.answer.title': 'Today you get to\nmake something together.',
  'home.hero.answer.progress': '6 Moments together',
  'home.hero.waiting.eyebrow': 'YOUR PART IS READY',
  'home.hero.waiting.title': 'Waiting for\nLucía.',
  'home.hero.waiting.progress': '6 Moments together',
  'home.hero.ready.eyebrow': 'POM IS EXCITED',
  'home.hero.ready.title': 'You can reveal\nit now.',
  'home.hero.ready.progress': '6 Moments together',
  'home.hero.complete.eyebrow': 'NEW MEMORY',
  'home.hero.complete.title': 'It is now in\nyour History.',
  'home.hero.complete.progress': '7 Moments together',
  'moment.kind.question': 'QUESTION',
  'moment.kind.answered': 'ANSWERED',
  'moment.kind.ready': 'READY',
  'moment.kind.revealed': 'REVEALED',
  'moment.action.answer': 'Answer',
  'moment.action.remind': 'Remind Lucía',
  'moment.action.reveal': 'Reveal the Moment',
  'moment.today': "TODAY'S MOMENT",
  'moment.promptLabel': "TODAY'S QUESTION",
  'moment.prompt': 'What small thing Lucía did made you smile this week?',
  'moment.privacy': "You will answer without seeing each other's response.",
  'moment.partnerPending': 'Lucía has not answered yet',
  'moment.saved': 'Answer saved · waiting for Lucía',
  'moment.you': 'YOU',
  'moment.partner': 'LUCÍA',
  'moment.ownAnswer': '“The coffee you left ready for me.”',
  'moment.partnerLocked': 'Answer ready · still hidden',
  'moment.partnerAnswer': '“When you hugged me and made dinner after a very long day.”',
  'moment.continue': 'Keep talking...',
  'moment.send': 'Send reply',
  'nav.home': 'Home',
  'nav.history': 'History',
  'nav.map': 'Map',
  'nav.pair': 'Pair',
  'pair.loading': 'Preparing your shared space...',
  'pair.setup.eyebrow': 'YOUR PRIVATE SPACE',
  'pair.setup.title': 'Start your story.',
  'pair.setup.body': 'Create a Pair and invite the other person, or join with the code they sent you.',
  'pair.setup.create': 'Create our Pair',
  'pair.setup.join': 'I have an Invitation',
  'pair.create.eyebrow': 'CREATE A PAIR',
  'pair.create.title': 'One date for both of you.',
  'pair.create.body': 'Your anniversary is stored once in your shared space.',
  'pair.create.anniversary': 'Your anniversary',
  'pair.create.placeholder': 'YYYY-MM-DD',
  'pair.create.submit': 'Create and invite',
  'pair.create.invalid': 'Enter a real date using YYYY-MM-DD.',
  'pair.create.future': 'The anniversary cannot be in the future.',
  'pair.join.eyebrow': 'JOIN A PAIR',
  'pair.join.title': 'Enter your shared code.',
  'pair.join.body': 'You will clearly see which Pair you are joining before accepting.',
  'pair.join.code': 'Invitation code',
  'pair.join.placeholder': 'ABCD-EF12',
  'pair.join.submit': 'Check Invitation',
  'pair.waiting.eyebrow': 'PENDING INVITATION',
  'pair.waiting.title': 'Waiting for your partner',
  'pair.waiting.body': 'Share the link or code. Only one person can use this Invitation.',
  'pair.waiting.code': 'ALTERNATIVE CODE',
  'pair.waiting.expires': 'The Invitation expires on',
  'pair.waiting.share': 'Share Invitation again',
  'pair.waiting.cancel': 'Cancel Invitation',
  'pair.waiting.renew': 'Create a new Invitation',
  'pair.waiting.cancelTitle': 'Cancel this Invitation?',
  'pair.waiting.cancelBody': 'The link and code will stop working. You can create another Invitation afterward.',
  'pair.waiting.cancelConfirm': 'Cancel Invitation',
  'pair.waiting.cancelled': 'This Invitation has been cancelled.',
  'pair.waiting.expired': 'This Invitation has expired.',
  'pair.waiting.shareIntro': 'Join our private Pair in Pomelo:',
  'pair.waiting.shareCode': 'Alternative code',
  'pair.active.eyebrow': 'ACTIVE PAIR',
  'pair.active.title': 'You are together.',
  'pair.active.body': 'This space is private and has only two members.',
  'pair.active.anniversary': 'SHARED ANNIVERSARY',
  'pair.active.members': 'MEMBERS',
  'pair.active.openHome': "Go to today's Moment",
  'pair.active.unlink': 'Unlink Pair',
  'pair.unlink.title': 'Unlink this Pair?',
  'pair.unlink.body': 'New Moments will stop. Permitted content will remain available in Archive Mode.',
  'pair.unlink.confirm': 'Unlink',
  'pair.archive.eyebrow': 'ARCHIVE MODE',
  'pair.archive.title': 'Your story is still here.',
  'pair.archive.body': 'The Pair is unlinked and no new Moments will be generated. Permitted content remains available as read-only.',
  'invite.loading': 'Checking the Invitation...',
  'invite.valid.eyebrow': 'PRIVATE INVITATION',
  'invite.valid.title': 'You have been invited to a Pair.',
  'invite.valid.body': 'Confirm the shared details before joining. Your personal Profile is already complete, so you will not enter the anniversary again.',
  'invite.valid.creator': 'INVITED BY',
  'invite.valid.anniversary': 'SHARED ANNIVERSARY',
  'invite.valid.accept': 'Join this Pair',
  'invite.success.eyebrow': 'ACTIVE PAIR',
  'invite.success.title': 'You are together.',
  'invite.success.body': 'The Invitation was used once and your private space is ready.',
  'invite.success.continue': 'Continue',
  'invite.cancelled.title': 'Invitation cancelled',
  'invite.cancelled.body': 'Ask your partner to create a new Invitation.',
  'invite.expired.title': 'Invitation expired',
  'invite.expired.body': 'The link is no longer valid. Your partner can generate another without creating a new Pair.',
  'invite.invalid.title': 'We could not find this Invitation',
  'invite.invalid.body': 'Check the link or enter the code again.',
  'invite.used.title': 'Invitation already used',
  'invite.used.body': 'This was a single-use link. If you already joined, sign in with the correct account.',
  'invite.pairFull.title': 'This Pair is already full',
  'invite.pairFull.body': 'Pomelo keeps every Pair private with exactly two members.',
  'invite.tryCode': 'Try another code',
  'pair.error.alreadyPaired': 'You already belong to an active Pair.',
  'pair.error.configuration': 'The backend is not configured in this environment yet.',
  'pair.error.invitationCancelled': 'The Invitation was cancelled. Ask for a new one.',
  'pair.error.invitationExpired': 'The Invitation has expired. Ask for a new one.',
  'pair.error.invitationInvalid': 'We could not find that Invitation.',
  'pair.error.invitationUsed': 'This Invitation has already been used.',
  'pair.error.invalidAnniversary': 'Check the anniversary date.',
  'pair.error.network': 'We could not connect. Try again.',
  'pair.error.notAllowed': 'You cannot perform this action for this Pair.',
  'pair.error.pairFull': 'This Pair already has two members.',
  'pair.error.profileIncomplete': 'Complete your personal Profile before continuing.',
  'pair.error.unexpected': 'Something went wrong. Try again.',
  'widget.title': "Today's Moment",
  'widget.action': 'Open Pomelo',
};

export const catalogs = { es, en } as const;
